=pod

=head1 NAME

PartCat - Electronic Components Cataloger and Organizer

=head1 SUMMARY

A simple project that aims to create a nice backend for a electronic component
catalog. This is only a backend, so the clients should be created separate from
this module.

=head1 SETUP

First of all, make sure you have L<App::cpanminus> installed. Then run the
classic C<cpanm --installdeps .> to install all the necessary dependencies. Then
All you need to do is run C<make init> to create the database and a sample
configuration file for the application, then all you need to do is edit the
C<config/main.conf> file and change the settings to fit your needs.

=head1 TESTING

To make sure everything is perfect for deployment you can run C<make test>,
which will run all the unit tests to make sure that you have a working system.

=head1 RUNNING

After setting the server up and running the tests, it finally comes time to run
the actual server instance. To do this simply run C<make run> and the server
will start up.

=head1 API DOCUMENTATION

To learn more about the API endpoints you should check the documentation of the
C<WebApplication.psgi> source file. There you'll have all the API documentation
in the POD section of the document.

=head1 AUTHOR

Nathan Campos <nathan@innoveworkhsop.com>

=head1 COPYRIGHT

Copyright (c) 2019- Innove Workshop Company.

=cut
